apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: combined
  namespace: ingress-apisix
spec:
  plugins:
    - name: limit-req
      enable: true
      config:
        rate: 5
        burst: 0
        nodelay: true
        key: "remote_addr"
    - name: jwt-auth
      enable: true
      config:
          key: iss
          value: "http://34.91.86.64:8083/auth/realms/myrealm"
