apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: combined
  namespace: ingress-apisix
spec:
  plugins:
    - name: limit-req
      enable: true
      config:
        rate: 5
        burst: false
        nodelay: true
        key: "remote_addr"
