apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: combined
  namespace: ingress-apisix
spec:
  plugins:
    - name: limit-req
      enable: true
      config:
        rate: 5
        burst: 0
        key: "remote_addr"
    - name: openid-connect
      enable: true
      config:
        client_id: "apisixuser"
        client_secret: "BwrEvSvXXgwySx41g2ZSNnfW3KBlhC62"
        discovery: "http://34.90.211.18:8083/auth/realms/myrealm/.well-known/openid-configuration"
        bearer_only: true
        realm: "myrealm"
        introspection_endpoint: "http://34.90.211.18:8083/auth/realms/myrealm/protocol/openid-connect/token/introspect"
        token_endpoint: "http://34.90.211.18:8083/auth/realms/myrealm/protocol/openid-connect/token"
        scope: "openid profile email"
