apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: combined
  namespace: ingress-apisix
spec:
  plugins:
    - name: limit-req
      enable: true
      config:
        rate: 5
        burst: false
        nodelay: false
        key: "remote_addr"
    - name: rate-limiting
      enable: true
      config:
        rate: 1
        burst: 0
        key: "remote_addr"
        rejected_code: 503
