apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: response-ratelimiting-example
plugin: response-ratelimiting
config:
  limits:
    limit_name:
      minute: 200
  policy: local
