apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: conversation-auth
  namespace: istio-ingress
spec:
  plugins:
    - name: jwt-auth
      enable: true
      config:
        algorithm: RS256
        jwks_uri: http://34.57.216.142:8083/auth/realms/odari/protocol/openid-connect/certs
        # issuer and audience are optional; add if you want extra checks
        issuer: http://34.57.216.142:8083/auth/realms/odari
        # audience: account
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key_type: var
        key: jwt_claim_clientId   # or jwt_claim_azp
        rejected_code: 429
    - name: echo     # remove after test
      enable: true
      config:
        before_body:
          - "azp = $jwt_claim_azp"
          - "clientId = $jwt_claim_clientId"
