apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: combined
  namespace: ingress-apisix
spec:
  plugins:
    - name: jwt-auth
      enable: true
      config:
        algorithm: RS256
        public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkiT/IX9mfp6tlugY2w2/
          Z3pEGc+gu91T6Q+f9L0RaRmK8fWJRCeM6xPAX86eSb+ezG73L+aI8ulL0o6qpzkD
          TYqWhGbQSUIPIj/4j+L7wr/YxLLz0EyjO7Ktx3qUw5IhtSCIQxuDj2hLVJ8c5l3n
          wpXK9pP+z+Dq31nzC1QK8PH5vep7gzF3lztC67wVn0aVkemWoO4u52wL8KwuyOLc
          Zgvse2WAjQ1tmupUyz+chK0P0Bd9cCrHKN3www1XKU8PmKUQW046pAO1igoX0UNM
          LgGbYXTKEeQn7jbcsjS/ox+vEsCNK8/XEyITQoa3ofh3U7JZA6Oe/s/9hFGm6l4W
          cQIDAQAB
          -----END PUBLIC KEY-----
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key_type: var
        key: jwt_claim_azp
        rejected_code: 429
        show_limit_quota_header: true
        policy: local
    - name: echo
      enable: true
      config:
        before_body:
          - "azp = $jwt_claim_azp"
          - "clientId = $jwt_claim_clientId"
    - name: prometheus
      enable: true
